language: node_js
node_js:
  - 8
branchs:
  only:
    - master
cache:
  directories:
    - node_modules
install:
  - npm install
scripts:
  - npm run build
after_success:
  - cd docs/.vuepress/dist
  - git init
  - git config --global user.name "${U_NAME}"
  - git config --global user.email "${U_EMAIL}"
  - git add -A
  - git commit -m 'auto deploy by Travis CI'
  - git push --quiet --force "https://${GH_TOKEN}@${GH_REF}" master:master
